blank_issues_enabled: false
contact_links:
  - name: Pertanyaan Umum / General Questions
    url: https://github.com/andriash001/dolanan_matematika/issues
    about: Gunakan Issues untuk pertanyaan, masukan, dan ide. / Use Issues for questions, feedback, and ideas.
